phony: tar

tar:
	cd .. && tar zcvf code128barcode.tgz --exclude fpdf.php \
								--exclude http_class.php \
								--exclude font \
								--exclude URW* \
								--exclude '*PrintIPP*' \
								\
								barcode/
